version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
