dist: xenial

git:
  depth: false

language: python

python:
  - 3.6
  - 3.7
  - 3.8

stages:
  - browser_test

cache: pip

jobs:
  include:
    - stage: browser_test
      name: "Caliban Browser Tests"
      install:
        - pip install -r browser/requirements.txt
        - pip install -r browser/requirements-test.txt
      script:
        - pytest browser --cov browser --pep8
