dist: xenial

git:
  depth: false

language: python

stages:
  - browser_test

cache: pip

script:
  - pytest --cov=benchmarking --pep8 benchmarking

jobs:
  include:
    - stage: browser_test
      name: "Caliban Browser Tests"
      python:
        - 3.5
        - 3.6
        - 3.7
        - 3.8
      install:
        - pip install -r browser/requirements.txt
        - pip install -r browser/requirements-test.txt
      script:
        - cd browser
        - pytest --cov . --pep8
