name: pre-commit-hooks

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: If needed, commit changes to the pull request
        if: failure()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git commit -am "Run pre-commit hooks"

          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push
