# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Frontend Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: 'visualizer/**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('visualizer/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-

    - name: Yarn Install
      working-directory: visualizer
      run: yarn

    - name: Lint
      working-directory: visualizer
      run: yarn lint

    - name: Unit Tests
      working-directory: visualizer
      run: yarn test -- --coverage
      env:
        CI: true

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        path-to-lcov: visualizer/coverage/lcov.info
        github-token: ${{ secrets.github_token }}
        flag-name: node-${{ matrix.node-version }}
        parallel: true

  # TODO: how to combine frontend/backend coverage
  # or separate into 2 different reports.
  # coveralls:
  #   name: Finish Coveralls
  #   needs: tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Coveralls Finished
  #       uses: coverallsapp/github-action@master
  #       with:
  #         base-path: visualizer
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         parallel-finished: true
