# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Frontend Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          frontend:
            - 'visualizer/**'

    - name: Use Node.js ${{ matrix.node-version }}
      if: steps.changes.outputs.frontend == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v2
      if: steps.changes.outputs.frontend == 'true'
      with:
        path: 'visualizer/**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('visualizer/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-

    - name: Yarn Install
      if: steps.changes.outputs.frontend == 'true'
      working-directory: visualizer
      run: yarn

    - name: Unit Tests
      if: steps.changes.outputs.frontend == 'true'
      working-directory: visualizer
      run: yarn test -- --coverage
      env:
        CI: true

    - name: Lint
      if: steps.changes.outputs.frontend == 'true'
      working-directory: visualizer
      run: yarn lint
    
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  coveralls:
    name: Finish Coveralls
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true